CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610_ALT=y
# Keep the sensor responsive longer before entering REST1.
CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=3264
# Allow nice!nano external power to stabilize before sensor initialization.
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=1000
